name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -ldflags="-s -w" -o sshpass.exe .

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: sshpass.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}